### ISSUE TITLE
Unclear how to handle empty messages

### ISSUE THREAD

**Issue by brycx** [paseto-standard/paseto-spec#17]
Before the new test-vectors repository was created (which is very nice to have btw), I think I remember some tests in the reference PHP implementation, that dealt with tokens that were created where message `m` was empty.

I haven't been able to find a related test-vector or a clarification in the spec on whether `m` can be empty or not. What is expected here? If it can be empty, perhaps this is worthwhile as a test for the test-vectors collection.

**Comment by paragonie-security** [comment]
That's a good point.

**Comment by paragonie-security** [comment]
This is resolved by #17; empty payloads are spelled out as invalid.
